doc:
  property:
  - allowedVMSizes: ''
  - vdcfarm: ''
  - account: ''
  - maxCPUCapacity: ''
  - description: ''
  - maxNumPublicIP: ''
  - uservdc: ''
  - g8client: ''
  - maxMemoryCapacity: ''
  - cloudspaceID: ''
  - location: ''
  - externalNetworkID: ''
  - maxDiskCapacity: GiB
  - maxNetworkPeerTransfer: ''
  - script: ''
links:
  consume:
  - argname: uservdc
    auto: false
    max: 100
    min: 0
    role: uservdc
  - argname: account
    auto: false
    max: 1
    min: 0
    role: account
  - argname: g8client
    auto: true
    max: 100
    min: 0
    role: g8client
  parent:
    auto: true
    optional: false
    role: vdcfarm
    argname: vdcfarm
recurring: []
